### PR TITLE
PHP/SQL/JSON - Endpoint create_user.php

### PR DESCRIPTION
**Pull request by dobs93**
Add end-point create_user.php. Add class UsersConnection. Simplify class DatabaseException. Add class DuplicateException.
SQL: Add user "users", which has access to add new database users.
JSON: Add credentials file usersLogon.json

### CODE REVIEW

**Comment by andreweissen** [comment]
What specifically do I need to do in order to test this in XAMPP? I received back a response of `{success: false, duplicate: false}` on submission of wellformed new user account details when I attached this to the front-end account creation handler. This leads me to believe I don't have my folders in the appropriate places. Have you successfully registered a test account, and if so, how?

**Comment by dobs93** [comment]
I made two corrections, so it worked for me now, although it wouldn't before. Sorry about that. You do need to make sure MariaDB user "users" gets added.

**Comment by andreweissen** [comment]
I've successfully imported `CreateDatabases.sql`, and I can see each of the five default user account levels and the three main databases in `phpmyadmin`. However, I still cannot create a new account and the five accounts seem to have no privileges in the `phpmyadmin` `mysql.users` table.

Can you walk me through specifically what must be done to configure this? I (and the other members of the front-end team) can't really proceed further on the front-end until I can see the integration with the back-end. A tutorial would be great.

**Comment by dobs93** [comment]
Okay. This may have to do with the difference between my testing environment (Fedora with Fedora's MariaDB & PHP packages) and XAMPP. I am downloading a Windows 10 VM so I can test using XAMPP for Windows.
I do not have anything called `phpmyadmin`, so I am assuming that is XAMPP specific. For me, when I login to MariaDB as `root` or any of the five additional accounts setup in `CreateDatabases.sql`, I see three databases, `UsersDB`, `PasswordsDB` and `BooksDB`. Perhaps XAMPP is adding the `phpmyadmin` in there somehow.

**Comment by andreweissen** [comment]
I'm using the November 12, 2015 build v. 3.2.2 of XAMPP. `phpmyadmin` is just the database administration tool XAMPP uses to display the dashboard and configuration options. I can see each of the accounts and the databases you listed, but I can't add a new account by means of the endpoint and the accounts lack permissions. Anyway, I'll go ahead and approve this if you can throw together a tutorial for us sometime soon.

**Review by andreweissen — APPROVED** [review]

**Pull request merged**
