### PR TITLE
JavaScript/CSS/JSON - Framework v.1 

### PR DESCRIPTION
**Pull request by andreweissen**
V.1 of the front-end framework, incorporating the development of element assemblers, scene builders, and default event handlers used to dynamically generate specific "scenes" on request without requiring page reloads or the like. Additionally included is a rough CSS framework that will see evolution and extensive encorporation of `@media` queries to handle desktop and mobile screen widths at a later date.

Outstanding issues and notes to self:
* Popup modal development required (make use of `jQuery.showCustomModal`)
* Fix ledger table bug with `nth-child(even)`
* `inaccessible.fade` inner functions require copy/paste reduction efforts
* Fix occasional bugginess in shifting of scene elements right prior to fade out
* Addition of POST request handler for inclusion in `inaccessible.api`
* Development of dashboard footer with meta links, etc.
* Handlers are presently noop'd
* Move username and password to a `<form>` element per GS

### CODE REVIEW

**Comment by dobs93** [comment]
I don't have experience with JS, so I'll just have to trust you on that, but I did see one problem in the JSON file. "Account" should be a 4-digit number; the account name can be looked-up in the Accounts table by searching for the 4-digit number with the user's userID.

**Comment by andreweissen** [comment]
I don't follow. Why can't the account name be provided as response data? The account number and associated user-configurable name should both be returned in response to a single GET request so there aren't two requests for every row. Ideally, they should be part of a nested object called `accountDetails` or something.

**Comment by dobs93** [comment]
Oops. I missed that the account number is there. Sorry. Its fine.

**Review by twbird18 — COMMENTED** [review]
When I load this (perhaps I've set something up wrong), all of the delete checkboxes are checked. I can see where you set them to false, but it isn't working. However, I'm able to solve that problem by removing the 
//checked: false,
from the configCheckbox section

Also, this doesn't really matter for our database purpose, but does the add JSON row button work for you? Those buttons don't add rows for me, but the offline rows work. Otherwise, it looks like a good start to me.

**Comment by andreweissen** [comment]
Yeah, I noticed the checkbox issue, but I forgot to add it to the list above.

The JSON functionality is the most important part of the program. The ability of the script to handle JSON returned from the database is the only way data can be displayed to the user. The offline row buttons ("offline" being a misnomer here; I used it to let myself know I could press those without the need for my server) simply test that sample object literals can be passed to the handler for display in the table. They'll be removed once actual functionality buttons are added.

Anyway, if you want to test the JSON functionality, you'll need to toss the files into a private server. It works nicely for me in my Apache dev server.

**Comment by twbird18** [comment]
I am running everything from Apache so I will play around when I have more time and see if I can determine why it isn't working on my end.  I didn't mean that we don't need JSON only that it doesn't matter whether I can test data appear at this moment.

**Comment by andreweissen** [comment]
If you can provide browser details and any console errors resulting from presses of the button, I can possibly figure out the issue.

**Comment by twbird18** [comment]
> If you can provide browser details and any console errors resulting from presses of the button, I can possibly figure out the issue.

No worries I figured it out. I forgot I can't just open the index file in order to be on the server.

**Review by twbird18 — APPROVED** [review]

**Pull request merged**
