### PR TITLE
CSS - Corrections & some new screen sizes

### PR DESCRIPTION
**Pull request by twbird18**
Fixes for #33, the mobile resize of `#dashboard-topbar-meta` & `#dashboard-topbar-navlinks` was in the wrong place which caused the lines to separate (Also, I moved the links to the bottom of the phone portrait size, but maybe I should put it back at the top?). Also corrected the `#login-container` JS problem, though I still need to work out the centering issue on a few screen sizes. 

I added a few more media query screen sizes - if your laptop screen is still bleeding off @andreweissen let me know. Unless your screen is smaller than ~600px it should fit. I wasn't planning on resizing for height differences, but I can. The `overflow:auto` doesn't work without a specific height given. I have to workout a few screen size issue still, but these are the sizes I plan to implement unless someone thinks we should be more specific than this. These should fit on most standard devices.

### CODE REVIEW

**Comment by andreweissen** [comment]
Dashboard topbar is now nicely aligned, animation is fixed, and the dashboard container no longer bleeds off the screen. Nicely done! The only strange behavior now is the login module's placement; as seen in the image, it's pushed down on the page and slightly bleeds off just as the dashboard used to.

toofardown

**Comment by twbird18** [comment]
I'll try to figure out why it's doing that later. None of my responsiveness testing did that. The other things you pointed out, I had already known & thought about. It's related to trying to center the login, which is more difficult without fixed position. I may just abandon that. It's not very important. It just looks nicer.

**Review by andreweissen — APPROVED** [review]
My bad, I thought I had approved this.

**Comment by andreweissen** [comment]
Apparently there was a merge conflict preventing this request from being committed. I think I fixed it though.

**Pull request merged**
