### PR TITLE
SQL - Add a Users table; modify the Accounts table

### PR DESCRIPTION
**Pull request by dobs93**
The Users table and userID fields in Documents and Accounts are meant to allow multiple users' data to be stored in the database while keeping it strictly separate.

### CODE REVIEW

**Comment by dobs93** [comment]
I also added an updated ERD.

**Review by andreweissen — COMMENTED** [review]
I don't see any breakage, but I'm curious: why the inclusion of the Draw.io `.xml` file? Is that for documentation purposes or does it have a planned display usage in the front-end side of the program via a viewer like Draw.io's [`viewer.min.js`](https://www.draw.io/js/viewer.min.js)?

Additionally, do you think the ERDs (and I guess other assorted diagrams/images/screenshots) should be placed in a separate subdirectory in `Documentation` or in a directory called `Images` in the metafolder or something? It's not strictly necessary, but it might be good to have another layer of organization specifically for images. Thoughts?

**Comment by twbird18** [comment]
The updated ERD has 2 Vendors listed. I believe one of those is supposed to be the Customer ID.

**Comment by dobs93** [comment]
Andrew: I just included the Draw.io XML file in case any of you wanted to open it to edit the formatting, plus, it will be in the cloud. I do not mind adding a new folder under Documentation, but I'd prefer to name it Figures.

Jennifer: Thanks for noticing the problem. You are right, I'll make that change.

**Review by andreweissen — APPROVED** [review]
Based on your response, I've moved the two ERD files into a subdirectory of `/Documentation` called `/Figures`. Assuming you and Jennifer have no further concerns, I think we can merge now.

**Pull request merged**
