### PR TITLE
JavaScript - Testing code for login.php endpoint

### PR DESCRIPTION
**Pull request by andreweissen**
Some testing code illustrating the proper expected return of `{"isLogonSuccessful":false}` JSON data from the `login.php` endpoint. Code displays the JSON data in the browser console for testing purposes.

### CODE REVIEW

**Comment by dobs93** [comment]
I see you have it POSTing to login.php a JSON object. I had just anticipated a string "username=?&password=?", but if you prefer JSON, I can change login.php.

**Comment by andreweissen** [comment]
A string is what you're getting. `JSON.stringify` converts my wellformed JSON object into a query string. You could do the same by manually appending a set of URL fragments to the proper endpoint location in the browser searchbar. I removed it though because I realized the query request handler `inaccessible.sendRequest` already stringifies the JSON object so it's redundant in the login handler.

**Comment by andreweissen** [comment]
Turns out I was confusing `JSON.stringify` with `jQuery.params` which converts a JSON string object to a query string. I've implemented a serializing helper function that handles the passage of a string like `"username=test&password=test"` rather than a JSON object, so no need to change anything on your end.

**Review by dobs93 — APPROVED** [review]
Looks good to me.

**Pull request merged**
