### PR TITLE
PHP - Add customer endpoint

### PR DESCRIPTION
**Pull request by dobs93**
Add method PhpConnection::addCustomer(string,string,string); add end-point

add_customer.php.

### CODE REVIEW

**Comment by andreweissen** [comment]
I received back the JSON response `{"success":false,"duplicate":false}` with some test code, but I had a question. How do you envision this being used in the front-end? I was under the impression that the user would be able to add a new table row entry that would include information about the customer as part of the entry. Is there supposed to be a dedicated "Add customer" sidebar button and associated popup, and if so, what should successful submission of "name" and "address" data do to the interface from the user's point of view?

**Comment by dobs93** [comment]
I think it would be easier to have an add customer bar, and I was going to do one for vendor, too, which would work the same way as this. I think adding customers/vendors with documents/entries would complicate that functionality.

**Comment by dobs93** [comment]
We would not need to give the user feedback about a successfully added customer or vendor, but we can tell the user if it failed and whether or not it was due to the customer or vendor already existing.

**Comment by andreweissen** [comment]
So just to clarify, the sidebar should include four buttons for new entries, documents, vendors, and customers? And what I meant by "from the user's point of view" is this: what is supposed to happen in the interface when the user successfully submits some data and creates a new customer? Is a dedicated ledger table associated with each new customer and vendor?

**Comment by dobs93** [comment]
Only three "new" buttons are needed: document (which includes a new row in the Documents table and two or more new rows in the General Ledger table [the document's contents]), customer and vendor. Some documents are associated with either a specific customer or vendor, so when a user enters a document, ideally there would be a pull-down menu for customers if it is an "ARI" or "ARR" entry, for vendors if it is an "API" or "APD" entry, or neither if it is a "JE" entry.

**Comment by andreweissen** [comment]
Okay, now we're getting somewhere, but I'm still having some trouble visualizing what you have in mind as well as the whole bookeeping thing in general. A few more clarifications/questions:
* There will be two main table-based ways in which the data may be viewed:
  * a general ledger table that displays the specific double-entry account transactions with two table rows per document (credit and debit)
  * a document overview table that shows a general overview listing of all the documents, one table row per document. Correct?
* Pressing the "Add new document" sidebar button opens a popup modal. This modal has a dropdown menu allowing the user to choose a new document type out of the five possible documents. Based on the document type selected, the modal's second dropdown menu is populated with a list of either vendors or customers that the user has created thus far to which this new document is to be associated. The modal will also contain other dropdowns and input textboxes related to the account names and types to be credited and debited. Correct?
* Pressing "Add new customer" or "Add new vendor" also opens a modal. The submission of a new vendor or customer will create a new entry in the database to which new documents may applied, yes? So if I create a new vendor named "Baltimore Gas and Electric," I should be able to select that vendor from the second dropdown in the "Add new document" modal if I create a new Accounts Payable Invoice document?  
* For the table displaying a listing of all the documents (as opposed to the general ledger), what will be the column header names?
* For the general ledger, should there be a column related to account type (i.e. asset, equity, etc.)?

**Comment by dobs93** [comment]
1. Correct, except that a document may have a variable number of general ledger rows, so long as the total of the debits column equals the total of the credits column. I can implement logic to test that on the back-end.
2. Correct.
3. Correct.
4. Document name, type, vendor or customer (if applicable), isPosted (although we might be able to drop that one)
5. Doesn't have to be; most bookkeepers set their account numbers so it is easy to tell (e.g., asset accounts are 1xxx, liabilities 2xxx, etc.)

**Review by andreweissen — APPROVED** [review]
Sounds good; I have a better idea of how to proceed now. Thanks!

**Pull request merged**
