### PR TITLE
SQL - CreateDatabase

### PR DESCRIPTION
**Pull request by dobs93**
Just a SQL statement for building a GeneralLedger table in a new user's database.

### CODE REVIEW

**Review by andreweissen — CHANGES_REQUESTED** [review]
Can you move CreateDatabase into the Files directory, preferably into its own sql subdirectory? The superfolder in which README.md and Files exist is the meta directory, in which there will also be folders for screenshots and documentation once those are added. Thanks!

**Comment by dobs93** [comment]
As soon as I can figure out how...

**Comment by dobs93** [comment]
Done.

**Review by andreweissen — APPROVED** [review]
LGTM

**Pull request merged**
